name: ModcraftMC Custom Docker Compose SSH Deployment
description: Deploy a repository with docker-compose via SSH to a remote host.
branding:
  icon: anchor
  color: blue
inputs:
  ssh_private_key:
    description: The SSH private key used for logging into remote system.
    required: true
  ssh_host:
    description: The remote host name or IP address.
    required: true
  ssh_port:
    description: The remote port number.
    default: '22'
  ssh_user:
    description: The remote username.
    default: 'docker-deploy'
  docker_compose_prefix:
    description: A prefix to add to the deployed containers.
  docker_compose_filename:
    description: The docker-compose file name.
    default: docker-compose.yaml
  use_stack:
    description: Use docker stack instead of docker compose ("true" or "false").
    default: 'false'
  no_cache:
    description: Adds --no-cache flag to docker build command ("true" or "false").
    default: 'false'
  tar_package_operation_modifiers:
    description: Tar operation modifiers used while creating the package.
    default: '--exclude .git --exclude .github --exclude .gitignore --exclude .gitmodules --exclude .vscode'
  docker_compose_down:
    description: Execute docker-compose down ("true" or "false").
    default: 'false'
  dockerhub_username:
    description: Docker Hub username used for login.
  dockerhub_password:
    description: Docker Hub password used for login.
  directory:
    description: Directory
  exports:
    description: List of environment variables to export on the remote host.
  zero_down_time:
    description: Specify if docker try to avoid downtime when starting container (if set to true require <docker_container_name> to be set).
    default: 'false'
  docker_container_name:
    description: Used to identify container when scaling for zero down time.
  local_mode:
    description: use ssh or not
    default: 'false'
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    USE_DOCKER_STACK: ${{ inputs.use_stack }}
    NO_CACHE: ${{ inputs.no_cache }}
    TAR_PACKAGE_OPERATION_MODIFIERS: ${{ inputs.tar_package_operation_modifiers }}
    ZERO_DOWN_TIME: ${{ inputs.zero_down_time }}
    DOCKERHUB_USERNAME: ${{ inputs.dockerhub_username }}
    DOCKERHUB_PASSWORD: ${{ inputs.dockerhub_password }}
    DIRECTORY: ${{ inputs.directory }}
    EXPORTS: ${{ inputs.exports }}
    DOCKER_CONTAINER_NAME: ${{ inputs.docker_container_name }}
